import { createServer,type Server } from 'node:http'
import { afterAll,beforeAll,describe,expect,it } from 'vitest'
import { runTool } from '../src/main/tools/registry'

const state={page:'home',supportEmail:'support@synthetic.invalid',products:[{name:'Red Widget',price:20,category:'A'},{name:'Blue Widget',price:12,category:'B'},{name:'Green Widget',price:15,category:'B'}],search:'',filter:'',submitted:false,revision:1}
let server:Server;let baseUrl=''
const context={taskId:'live-browser',e2e:{enabled:true as const,fixtureRoot:process.env.TEMP!,allowedProcessIds:[]}}
async function body(request:import('node:http').IncomingMessage){const chunks:Buffer[]=[];for await(const chunk of request)chunks.push(Buffer.from(chunk));return chunks.length?JSON.parse(Buffer.concat(chunks).toString('utf8')):{} as Record<string,unknown>}
beforeAll(async()=>{server=createServer(async(req,res)=>{res.setHeader('content-type',req.url?.startsWith('/api/')?'application/json':'text/html');if(req.url==='/'){res.end('<!doctype html><title>Companion Local Fixture</title><p>support@synthetic.invalid</p><a href="/products">Products</a>');return}if(req.url==='/products'){res.end('<!doctype html><title>Synthetic Products</title><table><tr><td>Blue Widget</td><td>12</td><td>B</td></tr></table>');return}if(req.url==='/api/state'){res.end(JSON.stringify(state));return}const input=await body(req);if(req.url!=='/api/navigate'&&Number(input.observedRevision)!==state.revision){res.statusCode=409;res.end(JSON.stringify({error:'stale observation'}));return}if(req.url==='/api/navigate')state.page=String(input.page);else if(req.url==='/api/fill')state.search=String(input.text);else if(req.url==='/api/filter')state.filter=String(input.category);else if(req.url==='/api/submit')state.submitted=true;else{res.statusCode=404;res.end('{}');return}state.revision++;res.end(JSON.stringify(req.url==='/api/filter'?state.products.filter(x=>x.category===state.filter):state))});await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const address=server.address();if(!address||typeof address==='string')throw new Error('No fixture address');baseUrl=`http://127.0.0.1:${address.port}`})
afterAll(async()=>new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve())))

describe('live localhost structured-browser E2E',()=>{
  it('serves a purpose-built page and observes support email/products',async()=>{const html=await fetch(baseUrl).then(x=>x.text());expect(html).toContain('<title>Companion Local Fixture</title>');const r=await runTool('browser.inspect',{baseUrl},context);expect(r.data).toMatchObject({supportEmail:'support@synthetic.invalid'});expect(Math.min(...(r.data as typeof state).products.map(x=>x.price))).toBe(12)})
  it('navigates, filters, and fills without submitting under approval',async()=>{expect((await runTool('browser.navigate',{baseUrl,page:'products'},context)).ok).toBe(true);expect((await runTool('browser.filter',{baseUrl,category:'B',observedRevision:2},context)).error).toBe('Approval required');const filtered=await runTool('browser.filter',{baseUrl,category:'B',observedRevision:2},context,true);expect(filtered.data).toHaveLength(2);const filled=await runTool('browser.fill',{baseUrl,text:'blue widget',observedRevision:3},context,true);expect(filled.ok).toBe(true);expect((filled.data as typeof state).submitted).toBe(false)})
  it('gates submit, rejects stale state, and rejects non-loopback endpoints',async()=>{expect((await runTool('browser.submit',{baseUrl,observedRevision:4},context)).error).toBe('Approval required');expect((await runTool('browser.submit',{baseUrl,observedRevision:1},context,true)).ok).toBe(false);expect((await runTool('browser.inspect',{baseUrl:'https://example.com'},context)).error).toContain('loopback')})
})
