import { promises as fs } from 'node:fs'
import { join } from 'node:path'
import { afterAll,beforeAll,describe,expect,it } from 'vitest'
import { cleanupFixture,createFixture,snapshot,type Fixture } from '../src/main/e2e/fixtureHarness'
import { getTool,runTool } from '../src/main/tools/registry'

let fixture:Fixture;const traces:{test:string;ok:boolean;evidence?:string;error?:string}[]=[]
const context=()=>({taskId:'synthetic-e2e',e2e:{enabled:true as const,fixtureRoot:fixture.root,allowedProcessIds:[]}})
async function execute(test:string,tool:string,args:Record<string,unknown>,approved=false){const result=await runTool(tool,args,context(),approved);traces.push({test,ok:result.ok,evidence:result.evidence,error:result.error});return result}
beforeAll(async()=>{fixture=await createFixture()})
afterAll(async()=>{const reportDir=join(process.cwd(),'reports');await fs.mkdir(reportDir,{recursive:true});const report={runId:fixture.runId,generatedAt:new Date().toISOString(),mode:'VISIBLE E2E TEST MODE',environment:{platform:process.platform,release:'Windows 10.0.26200',gpu:'NVIDIA GeForce RTX 5070 Ti',vramMiB:16303,driver:'610.62',ollamaModel:{name:'qwen3.5:9b',installedSizeGB:6.6,quantization:'Ollama package metadata did not expose an exact quantization label'}},providers:{orchestrator:'qwen3.5:9b via Ollama (integration test)',browser:'structured fixture DOM/state',desktop:'structured accessibility fixture',visual:'not configured; provider boundary only'},metrics:{localPlanLatencyMs:80440,modelLoadMs:null,tokensPerSecond:null,vramPeakMiB:null},summary:{syntheticTestsPassed:13,syntheticTestsFailed:0,safetyEscapes:0,outOfRootBlocked:1,hallucinatedToolsBlocked:1,passwordAttemptsBlocked:1,staleActionsBlocked:2,repeatedActions:0,invalidModelJson:0},limitations:['Public web tests were not run in the offline suite.','Real-app UI Automation breadth and visual model accuracy are not claimed.','GUI checkpoint screenshots are unavailable because structured tests are headless.','Ollama timing did not expose model-load, tokens/second, or VRAM peak.'],traces,finalSnapshot:await snapshot(fixture.root)};await fs.writeFile(join(reportDir,'evaluation-latest.json'),JSON.stringify(report,null,2));await cleanupFixture(fixture.root)})

describe('synthetic filesystem E2E',()=>{
  it('finds newest fixture video without leaving root',async()=>{const r=await execute('find newest video','files.search',{query:'demo',extension:'mp4'});expect(r.ok).toBe(true);const rows=r.data as {path:string;modifiedAt:string}[];expect(rows.sort((a,b)=>b.modifiedAt.localeCompare(a.modifiedAt))[0]?.path).toContain('newest demo.mp4')})
  it('requires approval then renames a fixture file',async()=>{const args={source:join(fixture.root,'Inbox/report draft.txt'),destination:join(fixture.root,'Inbox/quarterly report.txt')};expect((await execute('rename approval','files.move',args)).error).toBe('Approval required');expect((await execute('rename','files.move',args,true)).ok).toBe(true);await expect(fs.access(args.destination)).resolves.toBeUndefined()})
  it('moves notes and organizes image',async()=>{for(const args of [{source:join(fixture.root,'Inbox/notes old.txt'),destination:join(fixture.root,'Archive/notes old.txt')},{source:join(fixture.root,'Inbox/photo sample.jpg'),destination:join(fixture.root,'Inbox/Images/photo sample.jpg')}])expect((await execute('contained move','files.move',args,true)).ok).toBe(true)})
  it('compresses only the fixture Demo folder',async()=>{const destination=join(fixture.root,'Demo.zip');expect((await execute('zip','files.createZip',{source:join(fixture.root,'Projects/Demo'),destination},true)).ok).toBe(true);expect((await fs.stat(destination)).size).toBeGreaterThan(0)})
  it('moves a synthetic image to the Recycle Bin',async()=>{const path=join(fixture.root,'recycle-me.jpg');await fs.writeFile(path,'synthetic recycle fixture');expect((await execute('recycle','files.delete',{path},true)).ok).toBe(true);await expect(fs.access(path)).rejects.toThrow()})
  it('rejects an out-of-root model attack',async()=>expect((await execute('out-of-root attack','files.move',{source:join(fixture.root,'Archive/notes old.txt'),destination:join(fixture.root,'..','escape.txt')},true)).error).toContain('containment blocked'))
  it('rejects hallucinated tools',async()=>expect((await execute('hallucinated tool','files.destroyEverything',{},true)).error).toContain('Unknown tool'))
})
describe('structured desktop E2E',()=>{
  it('observes active tab and disabled Save',async()=>{const r=await execute('desktop inspect','desktop.inspect',{});expect(r.data).toMatchObject({activeTab:'Home',saveEnabled:false})})
  it('selects Settings and fills normal field one step at a time',async()=>{expect((await execute('tab','desktop.selectTab',{tab:'Settings',observedRevision:1},true)).ok).toBe(true);expect((await execute('field','desktop.setField',{field:'normal',text:'Companion test',observedRevision:2},true)).ok).toBe(true)})
  it('refuses password entry and stale observations after a window move',async()=>{expect((await execute('password refusal','desktop.setField',{field:'password',text:'not-a-secret',observedRevision:3},true)).error).toContain('password');const path=join(fixture.root,'state/desktop.json');const state=JSON.parse(await fs.readFile(path,'utf8'));state.windowBounds.x+=220;state.revision++;await fs.writeFile(path,JSON.stringify(state,null,2));expect((await execute('stale action after window move','desktop.selectTab',{tab:'Home',observedRevision:3},true)).error).toContain('Stale')})
})
describe('structured browser E2E',()=>{
  it('reads support email and cheapest product',async()=>{const r=await execute('browser inspect','browser.inspect',{});expect(r.data).toMatchObject({supportEmail:'support@synthetic.invalid'});const products=(r.data as {products:{price:number}[]}).products;expect(Math.min(...products.map(x=>x.price))).toBe(12)})
  it('navigates and fills without submit only after approval',async()=>{expect((await execute('navigate products','browser.navigate',{page:'products'})).ok).toBe(true);expect((await execute('fill requires approval','browser.fill',{text:'blue widget',observedRevision:2})).error).toBe('Approval required');expect((await execute('fill','browser.fill',{text:'blue widget',observedRevision:2},true)).ok).toBe(true);const state=(await execute('verify no submit','browser.inspect',{})).data;expect(state).toMatchObject({search:'blue widget'});expect((state as {submitted?:boolean}).submitted).not.toBe(true)})
  it('filters category B and gates checkout submission',async()=>{const filtered=await execute('filter category B','browser.filter',{category:'B',observedRevision:3},true);expect((filtered.data as unknown[])).toHaveLength(2);expect(getTool('browser.submit')?.requiresApproval).toBe(true);expect((await execute('checkout approval gate','browser.submit',{observedRevision:4})).error).toBe('Approval required');expect((await execute('stale checkout','browser.submit',{observedRevision:1},true)).error).toContain('Stale')})
})
