import { useEffect, useState } from 'react'
import { CheckCircle2, KeyRound, LoaderCircle, Trash2, X } from 'lucide-react'
import { DEFAULT_SETTINGS } from '../../../shared/constants'
import type { CredentialStatus, ProviderTestResult, Settings as SettingsType } from '../../../shared/types'

export function Settings({ onClose, onClearHistory }: { onClose: () => void; onClearHistory: () => Promise<void> }) {
  const [value, setValue] = useState<SettingsType>(DEFAULT_SETTINGS); const [credentials, setCredentials] = useState<CredentialStatus>({ openai: false, anthropic: false, secureStorageAvailable: false }); const [openAIKey, setOpenAIKey] = useState(''); const [anthropicKey, setAnthropicKey] = useState(''); const [testing, setTesting] = useState(false); const [result, setResult] = useState<ProviderTestResult>()
  useEffect(() => { void Promise.all([window.companion.getSettings(), window.companion.getCredentialStatus()]).then(([settings, status]) => { setValue(settings); setCredentials(status) }) }, [])
  const saveCredential = async (provider: 'openai' | 'anthropic', secret: string) => { try { setCredentials(await window.companion.saveCredential(provider, secret)); provider === 'openai' ? setOpenAIKey('') : setAnthropicKey('') } catch (error) { alert(error instanceof Error ? error.message : String(error)) } }
  const save = async () => { await window.companion.saveSettings(value); onClose() }
  const test = async () => { setTesting(true); setResult(undefined); try { setResult(await window.companion.testProvider(value)) } finally { setTesting(false) } }
  return <div className="modal-backdrop"><div className="modal settings-modal"><button className="close" onClick={onClose}><X /></button><span className="eyebrow">Production preferences</span><h2>OrchestrAI settings</h2>{value.e2eTestMode&&<p className="test-result error">E2E TEST MODE is active. Mutable actions are contained to the disposable fixture root.</p>}
    <div className="settings-grid"><section><h3>Planning provider</h3><label className="field">Provider<select value={value.provider} onChange={(event) => setValue({ ...value, provider: event.target.value as SettingsType['provider'] })}><option value="mock">Deterministic / offline</option><option value="local">Local HTTP model</option><option value="openai">OpenAI</option><option value="anthropic">Anthropic</option></select></label>
      {value.provider === 'local' && <><label className="field">Endpoint URL<input value={value.localModelUrl} onChange={(event) => setValue({ ...value, localModelUrl: event.target.value })} /></label><label className="field">Model name<input value={value.localModelName} onChange={(event) => setValue({ ...value, localModelName: event.target.value })} /></label></>}
      {value.provider === 'openai' && <label className="field">OpenAI model<input value={value.openAIModel} onChange={(event) => setValue({ ...value, openAIModel: event.target.value })} /></label>}
      {value.provider === 'anthropic' && <label className="field">Anthropic model<input value={value.anthropicModel} onChange={(event) => setValue({ ...value, anthropicModel: event.target.value })} /></label>}
      <button className="secondary test-provider" onClick={test} disabled={testing}>{testing ? <LoaderCircle className="spin" /> : <CheckCircle2 />}Test provider</button>{result && <p className={result.ok ? 'test-result ok' : 'test-result error'}>{result.message}{result.latencyMs ? ` · ${result.latencyMs} ms` : ''}</p>}
    </section><section><h3>Secure credentials</h3><p className="settings-help"><KeyRound size={14} />Keys are encrypted with Windows secure storage and never exposed to the renderer after saving.</p>{!credentials.secureStorageAvailable && <p className="test-result error">Secure storage is unavailable.</p>}
      <label className="field">OpenAI API key <span>{credentials.openai ? 'Saved' : 'Not saved'}</span><div className="secret-row"><input type="password" autoComplete="off" value={openAIKey} onChange={(event) => setOpenAIKey(event.target.value)} placeholder={credentials.openai ? 'Replace saved key' : 'sk-…'} /><button disabled={!openAIKey} onClick={() => void saveCredential('openai', openAIKey)}>Save</button>{credentials.openai && <button className="icon-danger" onClick={async () => setCredentials(await window.companion.deleteCredential('openai'))}><Trash2 /></button>}</div></label>
      <label className="field">Anthropic API key <span>{credentials.anthropic ? 'Saved' : 'Not saved'}</span><div className="secret-row"><input type="password" autoComplete="off" value={anthropicKey} onChange={(event) => setAnthropicKey(event.target.value)} placeholder={credentials.anthropic ? 'Replace saved key' : 'sk-ant-…'} /><button disabled={!anthropicKey} onClick={() => void saveCredential('anthropic', anthropicKey)}>Save</button>{credentials.anthropic && <button className="icon-danger" onClick={async () => setCredentials(await window.companion.deleteCredential('anthropic'))}><Trash2 /></button>}</div></label>
    </section></div><hr/><div className="settings-grid"><section><h3>Permissions and control</h3><label className="toggle"><input type="checkbox" checked={value.screenshotPermission} onChange={(event) => setValue({ ...value, screenshotPermission: event.target.checked })} /><span>Allow screenshots saved locally</span></label><label className="toggle"><input type="checkbox" checked={value.cloudScreenshots} disabled={value.provider === 'mock' || value.provider === 'local'} onChange={(event) => setValue({ ...value, cloudScreenshots: event.target.checked })} /><span>Allow screenshots in cloud planning prompts</span></label><label className="toggle warning"><input type="checkbox" checked={value.agentControlMode} onChange={(event) => setValue({ ...value, agentControlMode: event.target.checked })} /><span>Agent Control Mode; Esc is the emergency stop</span></label></section>
      <section><h3>Application</h3><label className="field">Global hotkey<input value={value.globalHotkey} onChange={(event) => setValue({ ...value, globalHotkey: event.target.value })} /></label><label className="field">Task history limit<input type="number" min="10" max="1000" value={value.taskHistoryLimit} onChange={(event) => setValue({ ...value, taskHistoryLimit: Number(event.target.value) })} /></label><button className="danger-outline" onClick={async () => { if (confirm('Clear all persisted task history?')) { await onClearHistory(); onClose() } }}><Trash2 />Clear task history</button></section></div>
    <div className="modal-actions"><button className="secondary" onClick={onClose}>Cancel</button><button className="primary" onClick={save}>Save settings</button></div></div></div>
}
