import type { ToolResult } from '../../../shared/types'
import { runPowerShell } from '../powershell'

const q=(v:string)=>`'${v.replaceAll("'","''")}'`
const common='Add-Type -AssemblyName UIAutomationClient;Add-Type -AssemblyName UIAutomationTypes;'
const root=(title:string)=>`$root=[Windows.Automation.AutomationElement]::RootElement;$w=$root.FindFirst([Windows.Automation.TreeScope]::Children,(New-Object Windows.Automation.PropertyCondition([Windows.Automation.AutomationElement]::NameProperty,${q(title)})));if(!$w){throw 'Fixture window not found'};`
const byId=(id:string)=>`$w.FindFirst([Windows.Automation.TreeScope]::Descendants,(New-Object Windows.Automation.PropertyCondition([Windows.Automation.AutomationElement]::AutomationIdProperty,${q(id)})))`

export async function inspectWindow(title:string):Promise<ToolResult>{try{const data=await runPowerShell<Record<string,unknown>>(`${common}${root(title)}$tab=${byId('MainTabs')};$active='';if($tab){$sp=$null;if($tab.TryGetCurrentPattern([Windows.Automation.SelectionPattern]::Pattern,[ref]$sp)){$selected=$sp.Current.GetSelection();if($selected.Count){$active=$selected[0].Current.Name}}};$normal=${byId('NormalField')};$password=${byId('PasswordField')};$save=${byId('SaveButton')};$b=$w.Current.BoundingRectangle;$revision="$($w.Current.ProcessId)|$($b.X),$($b.Y),$($b.Width),$($b.Height)|$active";[pscustomobject]@{title=$w.Current.Name;pid=$w.Current.ProcessId;activeTab=$active;normalField=if($normal){$v=$null;if($normal.TryGetCurrentPattern([Windows.Automation.ValuePattern]::Pattern,[ref]$v)){$v.Current.Value}else{''}}else{$null};passwordDetected=if($password){$password.Current.IsPassword}else{$false};saveEnabled=if($save){$save.Current.IsEnabled}else{$null};revision=$revision;windowBounds=@{x=$b.X;y=$b.Y;width=$b.Width;height=$b.Height}}|ConvertTo-Json -Compress`);return{ok:true,data,evidence:`Observed live window revision ${data.revision}`}}catch(error){return{ok:false,error:error instanceof Error?error.message:String(error)}}}

export async function selectLiveTab(title:string,tab:string,revision:string):Promise<ToolResult>{const before=await inspectWindow(title);if(!before.ok)return before;if(String((before.data as Record<string,unknown>).revision)!==revision)return{ok:false,error:'Stale desktop observation; inspect again before acting.'};try{await runPowerShell(`${common}${root(title)}$e=${byId(tab==='Settings'?'SettingsTab':'HomeTab')};if(!$e){throw 'Tab not found'};$p=$null;if(!$e.TryGetCurrentPattern([Windows.Automation.SelectionItemPattern]::Pattern,[ref]$p)){throw 'Tab is not selectable'};$p.Select();[pscustomobject]@{selected=${q(tab)}}|ConvertTo-Json -Compress`);return inspectWindow(title)}catch(error){return{ok:false,error:error instanceof Error?error.message:String(error)}}}

export async function setLiveField(title:string,field:string,text:string,revision:string):Promise<ToolResult>{const before=await inspectWindow(title);if(!before.ok)return before;if(String((before.data as Record<string,unknown>).revision)!==revision)return{ok:false,error:'Stale desktop observation; inspect again before acting.'};const id=/password/i.test(field)?'PasswordField':'NormalField';try{const meta=await runPowerShell<{isPassword:boolean;enabled:boolean}>(`${common}${root(title)}$e=${byId(id)};if(!$e){throw 'Field not found'};[pscustomobject]@{isPassword=$e.Current.IsPassword;enabled=$e.Current.IsEnabled}|ConvertTo-Json -Compress`);if(meta.isPassword)return{ok:false,error:'Typing into password fields is blocked.'};if(!meta.enabled)return{ok:false,error:'The target field is disabled.'};await runPowerShell(`${common}${root(title)}$e=${byId(id)};$p=$null;if(!$e.TryGetCurrentPattern([Windows.Automation.ValuePattern]::Pattern,[ref]$p)){throw 'Field does not support structured value entry'};$p.SetValue(${q(text)});[pscustomobject]@{updated=$true}|ConvertTo-Json -Compress`);return inspectWindow(title)}catch(error){return{ok:false,error:error instanceof Error?error.message:String(error)}}}
