import { clipboard } from 'electron'
import type { ToolDefinition, ToolResult } from '../../../shared/types'
import { runPowerShell } from '../powershell'

const win32 = `Add-Type -TypeDefinition @'
using System; using System.Runtime.InteropServices;
public static class CompanionInput {
  [DllImport("user32.dll")] public static extern bool SetCursorPos(int x, int y);
  [DllImport("user32.dll")] public static extern void mouse_event(uint flags, uint dx, uint dy, int data, UIntPtr extra);
  [DllImport("user32.dll")] public static extern void keybd_event(byte key, byte scan, uint flags, UIntPtr extra);
}
'@;`
const json = (body: string) => `${body}; [pscustomobject]@{success=$true}|ConvertTo-Json -Compress`
const q = (value: string) => `'${value.replaceAll("'", "''")}'`
const requireControl = (context: { agentControlMode?: boolean }): ToolResult | undefined => context.agentControlMode ? undefined : { ok: false, error: 'Agent Control Mode must be enabled for input automation.' }
async function execute(script: string): Promise<ToolResult> { try { const data = await runPowerShell(script, 10_000); return { ok: true, data, evidence: 'Input action completed' } } catch (error) { return { ok: false, error: error instanceof Error ? error.message : String(error) } } }

const click: ToolDefinition = { name: 'screen.click', description: 'Move the pointer and click an approved screen coordinate', risk: 'medium', requiresApproval: true, async run(args, context) { const blocked = requireControl(context); if (blocked) return blocked; const x = Math.round(Number(args.x)); const y = Math.round(Number(args.y)); if (!Number.isFinite(x) || !Number.isFinite(y) || x < 0 || y < 0) return { ok: false, error: 'Valid non-negative x/y coordinates are required.' }; const button = args.button === 'right' ? 'right' : 'left'; const flags = button === 'right' ? ['0x0008', '0x0010'] : ['0x0002', '0x0004']; return execute(`${win32}${json(`[CompanionInput]::SetCursorPos(${x},${y})|Out-Null; Start-Sleep -Milliseconds 80; [CompanionInput]::mouse_event(${flags[0]},0,0,0,[UIntPtr]::Zero); [CompanionInput]::mouse_event(${flags[1]},0,0,0,[UIntPtr]::Zero)`)}`) } }

const scroll: ToolDefinition = { name: 'screen.scroll', description: 'Scroll the active window by an approved amount', risk: 'medium', requiresApproval: true, async run(args, context) { const blocked = requireControl(context); if (blocked) return blocked; const amount = Math.max(-12, Math.min(12, Math.round(Number(args.amount ?? -3)))); return execute(`${win32}${json(`[CompanionInput]::mouse_event(0x0800,0,0,${amount * 120},[UIntPtr]::Zero)`)}`) } }

const keyMap: Record<string, number> = { ctrl: 0x11, control: 0x11, shift: 0x10, alt: 0x12, win: 0x5b, enter: 0x0d, escape: 0x1b, esc: 0x1b, tab: 0x09, backspace: 0x08, delete: 0x2e, space: 0x20, up: 0x26, down: 0x28, left: 0x25, right: 0x27, home: 0x24, end: 0x23, pageup: 0x21, pagedown: 0x22, a: 0x41, c: 0x43, v: 0x56, x: 0x58, f: 0x46, r: 0x52, s: 0x53, z: 0x5a }
const hotkey: ToolDefinition = { name: 'screen.hotkey', description: 'Press an approved keyboard shortcut', risk: 'medium', requiresApproval: true, async run(args, context) { const blocked = requireControl(context); if (blocked) return blocked; const keys = (Array.isArray(args.keys) ? args.keys : String(args.keys ?? '').split('+')).map((key) => String(key).trim().toLowerCase()).filter(Boolean); if (!keys.length || keys.length > 4 || keys.some((key) => !(key in keyMap))) return { ok: false, error: `Unsupported hotkey. Allowed keys: ${Object.keys(keyMap).join(', ')}` }; const codes = keys.map((key) => keyMap[key]!); const down = codes.map((code) => `[CompanionInput]::keybd_event(${code},0,0,[UIntPtr]::Zero)`).join(';'); const up = [...codes].reverse().map((code) => `[CompanionInput]::keybd_event(${code},0,2,[UIntPtr]::Zero)`).join(';'); return execute(`${win32}${json(`${down};Start-Sleep -Milliseconds 80;${up}`)}`) } }

const type: ToolDefinition = { name: 'screen.type', description: 'Type approved non-secret text into the focused non-password field', risk: 'medium', requiresApproval: true, async run(args, context) { const blocked = requireControl(context); if (blocked) return blocked; const text = String(args.text ?? ''); if (!text || text.length > 10_000) return { ok: false, error: 'Text must contain 1–10,000 characters.' }; if (args.sensitive || /(?:password|passcode|api[_ -]?key|secret|token)/i.test(text)) return { ok: false, error: 'Companion refuses to type text that appears to contain a secret.' }
  try { const focus = await runPowerShell<{ isPassword?: boolean }>(`Add-Type -AssemblyName UIAutomationClient; $e=[System.Windows.Automation.AutomationElement]::FocusedElement; [pscustomobject]@{isPassword=if($e){$e.Current.IsPassword}else{$false}}|ConvertTo-Json -Compress`); if (focus?.isPassword) return { ok: false, error: 'Typing into password fields is blocked.' } } catch { return { ok: false, error: 'Could not verify that the focused field is safe for typing.' } }
  const previous = clipboard.readText(); try { clipboard.writeText(text); const result = await hotkey.run({ keys: ['ctrl', 'v'] }, context); return result.ok ? { ...result, evidence: `Typed ${text.length} approved character(s); content omitted from audit log` } : result } finally { clipboard.writeText(previous) }
} }

const activeWindow: ToolDefinition = { name: 'screen.getActiveWindow', description: 'Read the title and process of the foreground window', risk: 'safe', requiresApproval: false, async run() { try { const data = await runPowerShell(`Add-Type -TypeDefinition @'\nusing System;using System.Runtime.InteropServices;using System.Text;public class Foreground{[DllImport("user32.dll")]public static extern IntPtr GetForegroundWindow();[DllImport("user32.dll")]public static extern int GetWindowText(IntPtr h,StringBuilder s,int n);[DllImport("user32.dll")]public static extern uint GetWindowThreadProcessId(IntPtr h,out uint p);}\n'@;$h=[Foreground]::GetForegroundWindow();$b=New-Object Text.StringBuilder 512;[Foreground]::GetWindowText($h,$b,512)|Out-Null;$pidValue=0;[Foreground]::GetWindowThreadProcessId($h,[ref]$pidValue)|Out-Null;$p=Get-Process -Id $pidValue -ErrorAction SilentlyContinue;[pscustomobject]@{title=$b.ToString();process=$p.ProcessName;pid=$pidValue}|ConvertTo-Json -Compress`); return { ok: true, data, evidence: JSON.stringify(data) } } catch (error) { return { ok: false, error: error instanceof Error ? error.message : String(error) } } } }

const recordToggle: ToolDefinition = { name: 'screen.recordToggle', description: 'Start or stop Windows Game Bar screen recording (Win+Alt+R)', risk: 'medium', requiresApproval: true, async run(_args, context) { const result = await hotkey.run({ keys: ['win', 'alt', 'r'] }, context); return result.ok ? { ...result, evidence: 'Toggled Windows Game Bar recording; recordings normally save under Videos\\Captures' } : result } }

export const inputTools = [activeWindow, click, type, hotkey, scroll, recordToggle]
